# .streamlit/secrets.toml

[connections.supabase]
SUPABASE_URL = "https://hcnfbpdvalnmhmmccdww.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhjbmZicGR2YWxubWhtbWNjZHd3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyNTIyMjgsImV4cCI6MjA3MzgyODIyOH0.28HhQczU_plni2ND4b2FX4RvX8gNWOEwZx6tdHggudQ"